[package]
name = "nex-ipc"
description = "Inter-thread communication primitives for Nexterm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nex-common = { workspace = true }
crossbeam-channel = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
