[package]
name = "nex-terminal"
description = "VT terminal emulation for Tonn"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nex-common = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
vte = { workspace = true }
bitflags = { workspace = true }
unicode-width = { workspace = true }
