[package]
name = "tonn"
description = "AI-first terminal emulator"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "tonn"
path = "src/main.rs"

[dependencies]
nex-common = { workspace = true }
nex-config = { workspace = true }
nex-terminal = { workspace = true }
nex-pty = { workspace = true }
nex-mux = { workspace = true }
nex-block = { workspace = true }
nex-mcp = { workspace = true }
nex-ai-session = { workspace = true }
nex-render = { workspace = true }
nex-ipc = { workspace = true }
nex-shell-integration = { workspace = true }

tokio = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
crossbeam-channel = { workspace = true }
parking_lot = { workspace = true }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
pollster = { workspace = true }
arboard = { workspace = true }
dirs = { workspace = true }
chrono = { workspace = true }
nex-token-save = { workspace = true }
alacritty_terminal = { workspace = true }
toml = { workspace = true }

