[package]
name = "nex-block"
description = "Block model for command-output pairs in Nexterm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nex-common = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
dashmap = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
nex-ipc = { workspace = true }
nex-token-save = { workspace = true }
crossbeam-channel = { workspace = true }
